# Torch NN with Word2Vec

In [6]:
import pandas as pd
import numpy as np
import random

from tqdm import tqdm
from collections import Counter

import torch
from torch.utils.data import Dataset, DataLoader
from torch import nn

import spacy
nlp = spacy.load("en_core_web_sm", enable=["tokenizer"])

In [7]:
df = pd.read_csv('../../../custom_dataset_v2_mini.csv', delimiter=";")
df.head()

,ID,Label,Text,word_count
0,25454,Google,We propose a new global entity disambiguation ...,33
1,5152,Google,Newton's laws and Newtonian mechanics in gener...,43
2,27268,Google,3 April 2017 Last updated at 09:17 BST Demand ...,35
3,29161,Google,Southern California contains a Mediterranean c...,32
4,45531,Google,NASA scientists discovered cyclopropenylidene ...,33

## Tokenizer

In [8]:
def preprocess(text):
  text = text.lower()
  text = text.replace('\n', ' ').replace('.', ' PUNCT ').replace('!', ' PUNCT ').replace('?', ' PUNCT ')
  tokens = [token.text for token in nlp(text)]
  return tokens

In [9]:
df['tokens'] = df.apply(lambda row: preprocess(row['Text']), axis=1)
df.head()

,ID,Label,Text,word_count,tokens
0,25454,Google,We propose a new global entity disambiguation ...,33,"[we, propose, a, new, global, entity, disambig..."
1,5152,Google,Newton's laws and Newtonian mechanics in gener...,43,"[newton, 's, laws, and, newtonian, mechanics, ..."
2,27268,Google,3 April 2017 Last updated at 09:17 BST Demand ...,35,"[3, april, 2017, last, updated, at, 09:17, bst..."
3,29161,Google,Southern California contains a Mediterranean c...,32,"[southern, california, contains, a, mediterran..."
4,45531,Google,NASA scientists discovered cyclopropenylidene ...,33,"[nasa, scientists, discovered, cyclopropenylid..."

In [10]:
corpus = [token for row in df['tokens'] for token in row]
len(corpus)

18528300

## Subsampling

In [11]:
token_freq = Counter(corpus)
total_token_count = sum(token_freq.values())
token_freq_prob = {token: count / total_token_count for token, count in token_freq.items()}

In [12]:
COMMON_TOKENS_THRESHOLD = 1e-5

def subsampling_prob(token):
  return ((token_freq_prob[token] - COMMON_TOKENS_THRESHOLD) / token_freq_prob[token]) - np.sqrt(COMMON_TOKENS_THRESHOLD / token_freq_prob[token])

keep_prob = {token: subsampling_prob(token) for token in token_freq_prob}
keep_prob

{'we': np.float64(0.9367744014108392),
 'propose': np.float64(0.49228516106118436),
 'a': np.float64(0.9762758298256),
 'new': np.float64(0.9152630022357242),
 'global': np.float64(0.7211628643441171),
 'entity': np.float64(-0.6210440486853337),
 'disambiguation': np.float64(-10.324014942044277),
 '(': np.float64(0.9324035909685575),
 'ed': np.float64(-0.6869492499843146),
 ')': np.float64(0.9321744347288932),
 'model': np.float64(0.7679520392579176),
 'based': np.float64(0.8384595502841011),
 'on': np.float64(0.9578897129336854),
 'contextualized': np.float64(-6.415394970020651),
 'embeddings': np.float64(-0.9626825116194394),
 'of': np.float64(0.9767124949960457),
 'words': np.float64(0.6602812025512799),
 'and': np.float64(0.9796603202951865),
 'entities': np.float64(-0.4454308712031771),
 'PUNCT': np.float64(0.9863565747736376),
 ' ': np.float64(0.9844767235918273),
 'our': np.float64(0.9066165006141025),
 'is': np.float64(0.9659993075990735),
 'bidirectional': np.float64(-6.984158755097639),
 'transformer': np.float64(-3.32393742995327),
 'encoder': np.float64(-3.4283724830226596),
 'i': np.float64(0.9631459322106016),
 'e': np.float64(0.6777640465056263),
 ',': np.float64(0.9828893045206424),
 'bert': np.float64(-3.375431677368475),
 'produces': np.float64(0.09503367847662558),
 'newton': np.float64(-0.4638519205751142),
 "'s": np.float64(0.9528339845913688),
 'laws': np.float64(0.6150724526768172),
 'newtonian': np.float64(-6.245426262409374),
 'mechanics': np.float64(-0.06832713429161463),
 'in': np.float64(0.972404209358765),
 'general': np.float64(0.6908933401954575),
 'were': np.float64(0.9231010007908023),
 'first': np.float64(0.8909519449125208),
 'developed': np.float64(0.7082160289758056),
 'to': np.float64(0.9785229508237513),
 'describe': np.float64(0.26883498894133984),
 'how': np.float64(0.9038315383570332),
 'forces': np.float64(0.5656386365609285),
 'affect': np.float64(0.26883498894133984),
 'idealized': np.float64(-1.8232691011084659),
 'point': np.float64(0.7514915234847546),
 'particles': np.float64(0.30095003579526075),
 'rather': np.float64(0.8171058918410382),
 'than': np.float64(0.9063702286596403),
 'three': np.float64(0.7854591803128494),
 '-': np.float64(0.9611292241513024),
 'dimensional': np.float64(0.24583290358015975),
 'objects': np.float64(0.5326329533418055),
 'however': np.float64(0.8722267385188804),
 'real': np.float64(0.7872866130845815),
 'life': np.float64(0.869272720529333),
 'matter': np.float64(0.6863220061249153),
 'has': np.float64(0.9314852215263572),
 'extended': np.float64(0.28417635005494396),
 'structure': np.float64(0.6485876536708965),
 'attaphysics': np.float64(-197.89486982012394),
 'mathematics': np.float64(-0.14783655787960748),
 'are': np.float64(0.9529509178162756),
 'considered': np.float64(0.6403647355370728),
 'be': np.float64(0.9490252567473613),
 'specialized': np.float64(-0.1814778779752808),
 'field': np.float64(0.7186454008974414),
 'theoretical': np.float64(0.12657487917248122),
 'knowledge': np.float64(0.7204698918813477),
 '3': np.float64(0.7908333965586265),
 'april': np.float64(0.365949998525465),
 '2017': np.float64(0.19434805547141054),
 'last': np.float64(0.8323444435949382),
 'updated': np.float64(0.2552592696718311),
 'at': np.float64(0.9413314304455703),
 '09:17': np.float64(-21.8327511845298),
 'bst': np.float64(0.05424522235059037),
 'demand': np.float64(0.5307127656917386),
 'for': np.float64(0.9649592729137334),
 'property': np.float64(0.5119841299822494),
 'china': np.float64(0.6302865113315723),
 'top': np.float64(0.7662581365329961),
 'cities': np.float64(0.6578661322120372),
 'so': np.float64(0.9238648458130772),
 'red': np.float64(0.6448575364523396),
 'hot': np.float64(0.6850364832884153),
 'some': np.float64(0.9155942347900085),
 'couples': np.float64(-0.6456267428645355),
 'even': np.float64(0.8854709754925427),
 'undergoing': np.float64(-1.6190938045041463),
 'fake': np.float64(0.020692675626502344),
 'divorces': np.float64(-13.983154955030978),
 'order': np.float64(0.8127358521779875),
 'buy': np.float64(0.6752579981644636),
 'economic': np.float64(0.7332750556064183),
 'social': np.float64(0.8571297876898445),
 'infrastructure': np.float64(0.5299386824553891),
 'southern': np.float64(0.3389543667734383),
 'california': np.float64(0.31139226467528164),
 'contains': np.float64(0.5213928530171414),
 'mediterranean': np.float64(-0.5146253500339613),
 'climate': np.float64(0.6965737816469906),
 'with': np.float64(0.9575658267510331),
 'infrequent': np.float64(-11.874513946239542),
 'rain': np.float64(0.3580268449434193),
 'many': np.float64(0.8988482111163023),
 'sunny': np.float64(-0.655721341861204),
 'days': np.float64(0.7291203533646031),
 'summers': np.float64(-2.556518834658502),
 'dry': np.float64(0.6054156140896011),
 'while': np.float64(0.9103948774183301),
 'winters': np.float64(-2.5890352808459256),
 'bit': np.float64(0.7008025334156055),
 'warm': np.float64(0.5759372618200951),
 'or': np.float64(0.9460616530093883),
 'mild': np.float64(-0.4418158717719946),
 'wet': np.float64(0.22231718292769498),
 'serious': np.float64(0.600394139024963),
 'nasa': np.float64(0.20317092272548487),
 'scientists': np.float64(0.657622007739574),
 'discovered': np.float64(0.49676977111425524),
 'cyclopropenylidene': np.float64(-24.1242899400413),
 'the': np.float64(0.984270388410068),
 'atmosphere': np.float64(0.6584338902421307),
 'saturn': np.float64(-1.311454451578983),
 'moon': np.float64(0.40383636598470085),
 'titan': np.float64(-4.053515149059547),
 'simple': np.float64(0.7013614844874605),
 'carbon': np.float64(0.5484847336223113),
 'molecule': np.float64(-0.7423836938470484),
 'never': np.float64(0.8395671734296113),
 'been': np.float64(0.913902217490426),
 'seen': np.float64(0.7456003921535661),
 'an': np.float64(0.9410499072500397),
 'before': np.float64(0.8717090386604559),
 'long': np.float64(0.8645422442041583),
 'one': np.float64(0.928044636645561),
 'big': np.float64(0.768144214119283),
 'disappointment': np.float64(-0.438223414929597),
 'soak': np.float64(-0.697686191063134),
 'your': np.float64(0.9287656290904954),
 'feet': np.float64(0.4986262939181168),
 '15': np.float64(0.6265093338407317),
 '20': np.float64(0.6729844745408587),
 'minutes': np.float64(0.7412243205489352),
 'every': np.float64(0.8296422856643414),
 'night': np.float64(0.8017159492044732),
 'about': np.float64(0.9163652555966297),
 'week': np.float64(0.7240664843664477),
 'add': np.float64(0.6351305490516521),
 'nice': np.float64(0.7592692353242058),
 'smell': np.float64(0.3530537514479325),
 'squeeze': np.float64(-1.5153711786009594),
 'juice': np.float64(-0.02816069736349891),
 'lemon': np.float64(-0.5790083528450435),
 'into': np.float64(0.9101999552521689),
 '"': np.float64(0.951478926502531),
 'great': np.float64(0.8814813706091438),
 'news': np.float64(0.679337321322715),
 'bob': np.float64(0.19597118426885118),
 'popularity': np.float64(0.22082967967666634),
 'up': np.float64(0.9153959505895833),
 'papers': np.float64(-0.15395838492225578),
 'have': np.float64(0.9469306546245727),
 'numbers': np.float64(0.5071987935781009),
 'like': np.float64(0.9277862381661395),
 'these': np.float64(0.8948905875251726),
 'knew': np.float64(0.668003176227358),
 'it': np.float64(0.9646405877821731),
 'that': np.float64(0.9643499238743513),
 'as': np.float64(0.9561909142467917),
 'soon': np.float64(0.6921744378846139),
 'could': np.float64(0.9149891496407782),
 'iron': np.float64(0.009738052192777458),
 'out': np.float64(0.9154305980683537),
 'few': np.float64(0.82492663449673),
 'fans': np.float64(0.2889090646431383),
 'would': np.float64(0.9164176733452977),
 'happy': np.float64(0.7179822968486991),
 'ethan': np.float64(-2.7998744244582117),
 'sat': np.float64(0.5823966547687796),
 'piano': np.float64(-0.31077240874231093),
 'his': np.float64(0.923601153332407),
 'teacher': np.float64(0.6253657801527903),
 'studio': np.float64(-0.022087884370711852),
 'he': np.float64(0.9370466317641254),
 'felt': np.float64(0.738302631601004),
 'guilty': np.float64(-0.10903908117056593),
 'because': np.float64(0.8862566999519297),
 'had': np.float64(0.9301066115053793),
 'not': np.float64(0.9441689993452776),
 'practiced': np.float64(0.037845827506467034),
 'assignment': np.float64(-0.6162361394543348),
 'thought': np.float64(0.7747765917169064),
 'should': np.float64(0.8729208251159751),
 'just': np.float64(0.9066747633271006),
 'pretend': np.float64(-1.7510739039526588),
 'very': np.float64(0.8897260250100923),
 'bad': np.float64(0.760899682030919),
 'day': np.float64(0.8771723012093484),
 'june': np.float64(0.40711945890705464),
 '16': np.float64(0.42684620690220154),
 '2007': np.float64(0.12456051885272157),
 'abc': np.float64(0.004141326712195137),
 'began': np.float64(0.7301759866892066),
 'phase': np.float64(0.2958558920504705),
 'imaging': np.float64(-0.09443386741409054),
 'campaign': np.float64(0.3710898760379364),
 'upcoming': np.float64(-0.2345156472413703),
 '08': np.float64(-3.912504338803149),
 'season': np.float64(0.6256786125468708),
 'start': np.float64(0.7627338399691029),
 'here': np.float64(0.8755086505284805),
 'also': np.float64(0.9252485008500286),
 'by': np.float64(0.9426396066014955),
 'troika': np.float64(-26.972897727219067),
 'air': np.float64(0.7774837274129073),
 'design': np.float64(0.7208400753466635),
 'was': np.float64(0.958523887567558),
 'intended': np.float64(0.2565807691927148),
 'pause': np.float64(-1.7687071737302729),
 'gather': np.float64(-0.10534123752124291),
 'friends': np.float64(0.8026951936724049),
 'then': np.float64(0.8764166889190589),
 'fall': np.float64(0.5502145101275528),
 'love': np.float64(0.8060503636380325),
 'girlfriend': np.float64(0.20237926727334088),
 'married': np.float64(0.08836506138268563),
 'wife': np.float64(0.5828177806950514),
 'plus': np.float64(0.4745224467038397),
 'able': np.float64(0.821771733794242),
 'get': np.float64(0.8930783862596279),
 'job': np.float64(0.7547314959713427),
 'hat': np.float64(-0.34900773507817195),
 'position': np.float64(0.5264119981088393),
 'nbc': np.float64(-1.9405133008083342),
 'television': np.float64(0.5312910656478949),
 'station': np.float64(0.5145418929955552),
 '[': np.float64(0.8949642889018733),
 'substeps': np.float64(0.7858326049422641),
 ']': np.float64(0.896418347258596),
 'make': np.float64(0.8910685946740566),
 'couple': np.float64(0.562158216797896),
 'offerings': np.float64(-0.9549883960660233),
 'you': np.float64(0.9518444106003685),
 'know': np.float64(0.8514412795093703),
 'kids': np.float64(0.6619439670614395),
 'will': np.float64(0.9248083154532462),
 'if': np.float64(0.9268116683925256),
 "'re": np.float64(0.8494276101646765),
 'trying': np.float64(0.7111021062799678),
 'recipe': np.float64(-0.5187147370785716),
 'example': np.float64(0.7860950933739037),
 'making': np.float64(0.8149576257978512),
 'meatloaf': np.float64(-4.630669090887626),
 'time': np.float64(0.9207335085809777),
 'consider': np.float64(0.7174104344654024),
 'having': np.float64(0.7877366219230171),
 'grilled': np.float64(-0.36447614868538075),
 'cheese': np.float64(0.5690447138958032),
 'sandwich': np.float64(0.4817249344589452),
 'children': np.float64(0.7683632936925952),
 'need': np.float64(0.8499859988987838),
 'deal': np.float64(0.6434986644404872),
 'understand': np.float64(0.7569832312649989),
 'appropriate': np.float64(0.450304017974618),
 'behavior': np.float64(0.6375355727013268),
 'give': np.float64(0.7935491707276829),
 'them': np.float64(0.9094132274698753),
 'clarifying': np.float64(-2.9574892586675965),
 'rules': np.float64(0.554125575653378),
 'set': np.float64(0.7855032083235702),
 'chore': np.float64(-1.133882758478319),
 'schedule': np.float64(0.3516796317411603),
 'use': np.float64(0.8868024230303512),
 'same': np.float64(0.837329729659628),
 'other': np.float64(0.9126100649365377),
 'society': np.float64(0.7499785082098916),
 'limited': np.float64(0.6346442522642768),
 'resources': np.float64(0.7103880599247813),
 'decide': np.float64(0.3921458235774783),
 'best': np.float64(0.8484399823252748),
 'those': np.float64(0.8534462557887501),
 'spending': np.float64(0.4352782614548858),
 'thousands': np.float64(0.48963906646172856),
 'dollars': np.float64(0.34563444001291904),
 'child': np.float64(0.6787242332935559),
 'unlikely': np.float64(-0.10167469708443799),
 'recover': np.float64(-0.23208353075496685),
 'inefficient': np.float64(-1.842033194651219),
 'important': np.float64(0.8567212640489075),
 'remember': np.float64(0.6017585105652162),
 'democracy': np.float64(0.2811759621779083),
 'almost': np.float64(0.6907705566602527),
 'always': np.float64(0.852736469982807),
 'putting': np.float64(0.30704601221295486),
 'politicians': np.float64(-0.013149030292562758),
 'no': np.float64(0.8967539542085083),
 'win': np.float64(0.5515854336375916),
 'situations': np.float64(0.3620210773371725),
 'spend': np.float64(0.583377481931495),
 'too': np.float64(0.8600221904964975),
 'much': np.float64(0.868822100575544),
 'washington': np.float64(0.02204015805269477),
 'career': np.float64(0.5707206673830447),
 'politician': np.float64(-1.5585954102967676),
 'believe': np.float64(0.7852607371512951),
 'american': np.float64(0.728566836049383),
 'dream': np.float64(0.4214870036993382),
 'do': np.float64(0.9208242927306823),
 "n't": np.float64(0.9334036188574348),
 'what': np.float64(0.908384309967797),
 'told': np.float64(0.7650429093286052),
 'court': np.float64(0.607447532128371),
 'novorossiysk': np.float64(-11.874513946239542),
 'gave': np.float64(0.6836708205865887),
 'two': np.float64(0.8750473372560894),
 'dancers': np.float64(-0.8612715107750718),
 '10': np.float64(0.7399834206845991),
 'jail': np.float64(-0.8749703927201798),
 'each': np.float64(0.8577397399007122),
 'third': np.float64(0.623473577472502),
 'others': np.float64(0.8148562856894679),
 'received': np.float64(0.5365969354924074),
 'fines': np.float64(-2.6562145759237143),
 'charges': np.float64(0.10693780241190765),
 'petty': np.float64(-2.9993227625934553),
 'hooliganism': np.float64(-11.874513946239542),
 'prosecutors': np.float64(-3.0861720498019842),
 'lesipovski': np.float64(-197.89486982012394),
 'lawyers': np.float64(-1.861097626114268),
 'described': np.float64(0.38942055557809657),
 'trial': np.float64(0.14512887755852644),
 'apocalyptic': np.float64(-9.133693964024781),
 'supposed': np.float64(0.28655304530855763),
 'pedophile': np.float64(-8.481938901607561),
 'ring': np.float64(0.16448610401283026),
 'run': np.float64(0.7247792679266094),
 'pizza': np.float64(0.6831462285383854),
 'place': np.float64(0.8923951675034346),
 'dc': np.float64(-0.8889195454438125),
 'where': np.float64(0.8688382714259523),
 'famous': np.float64(0.36508246165012903),
 'frequent': np.float64(-0.011678667226937667),
 'there': np.float64(0.9252065032458027),
 'whole': np.float64(0.6938000705642834),
 'slew': np.float64(-6.783916415295266),
 'evidence': np.float64(0.6819570138491614),
 'guy': np.float64(0.5380831980557812),
 'who': np.float64(0.9023257159615826),
 'ran': np.float64(0.5293558439801731),
 'came': np.float64(0.7953050636128045),
 'club': np.float64(0.650671178792938),
 'got': np.float64(0.8399411285903877),
 'picture': np.float64(0.42451795246610086),
 'girl': np.float64(0.5854582368744816),
 'nothing': np.float64(0.7208862520039998),
 'acceptable': np.float64(-0.023597450154093425),
 'walking': np.float64(0.6048124863010358),
 'around': np.float64(0.8698297594749766),
 'showing': np.float64(0.4552713540243447),
 'underwear': np.float64(-1.7337068224437135),
 'civilized': np.float64(-3.2250514619344113),
 'potentially': np.float64(0.5503864986943381),
 'violation': np.float64(-0.714112837687668),
 'indecency': np.float64(-4.8247666762056705),
 'man': np.float64(0.7827469524848051),
 'want': np.float64(0.8393551165897759),
 'see': np.float64(0.8578961526983214),
 'people': np.float64(0.9150913856017032),
 'put': np.float64(0.7778248067217666),
 'public': np.float64(0.8145949688948173),
 'view': np.float64(0.7202842850021097),
 'all': np.float64(0.9259887538188813),
 'clergy': np.float64(-2.292210002834642),
 'appointments': np.float64(-1.0439188739558298),
 'made': np.float64(0.860917561903566),
 'fixed': np.float64(0.34088135835983463),
 'annually': np.float64(-0.597352887484337),
 'resident': np.float64(-1.5884202866397288),
 'bishop': np.float64(-1.3000120920743505),
 'advice': np.float64(0.5040867977198553),
 'annual': np.float64(0.18859901933519707),
 'conference': np.float64(0.06994201443489045),
 'cabinet': np.float64(-0.8959902198093975),
 'which': np.float64(0.9135029253835085),
 'composed': np.float64(-0.21305417798455728),
 'area': np.float64(0.7838344411533935),
 'provostdean': np.float64(-35.43752258408224),
 'full': np.float64(0.7660615164056701),
 'name': np.float64(0.7080067925148615),
 'selected': np.float64(-0.04058894158634041),
 'candidate': np.float64(0.20474809106319347),
 'god': np.float64(0.5038624767123436),
 'mankind': np.float64(-1.2131717171597918),
 'please': np.float64(0.6459344071916779),
 'state': np.float64(0.7948603695224589),
 'credentials': np.float64(-2.556518834658502),
 'may': np.float64(0.9027674666500379),
 'continue': np.float64(0.7331122833050308),
 'decision': np.float64(0.6830147028180973),
 'process': np.float64(0.7728071803823533),
 'well': np.float64(0.8874480645337035),
 "'ve": np.float64(0.8355194725838949),
 'most': np.float64(0.8891409584934564),
 'recently': np.float64(0.6430425122884886),
 'am': np.float64(0.8099230459382358),
 'prophet': np.float64(-6.415394970020651),
 'already': np.float64(0.7381096993250827),
 'designated': np.float64(-0.796296676167797),
 'perform': np.float64(0.42684620690220154),
 'miracles': np.float64(-6.245426262409374),
 'through': np.float64(0.902293610476095),
 'my': np.float64(0.9299033186449058),
 'son': np.float64(0.47267938613837485),
 'but': np.float64(0.9423391102044271),
 'unable': np.float64(0.31031245566754667),
 'speak': np.float64(0.39175848321272044),
 'word': np.float64(0.6288697039148404),
 'scripture': np.float64(-5.384697663866611),
 'due': np.float64(0.7922943240417027),
 'injuries': np.float64(0.28773362151663057),
 'from': np.float64(0.9443253863516468),
 'accident': np.float64(0.200789771415683),
 'sustained': np.float64(-0.22485936985991312),
 'main': np.float64(0.6617865775796288),
 'parties': np.float64(0.3676756656326398),
 'british': np.float64(0.5837959144886335),
 'irish': np.float64(-0.08731334938169988),
 'governments': np.float64(0.47426021327358714),
 'resolve': np.float64(-0.40013327267057247),
 'crisis': np.float64(0.32298254138375465),
 'stormont': np.float64(-6.984158755097639),
 'solutions': np.float64(0.5605509206044015),
 'found': np.float64(0.8345819480650029),
 'issues': np.float64(0.7851723732305329),
 'over': np.float64(0.9069326534633462),
 'paramilitarism': np.float64(-19.948042262592132),
 'welfare': np.float64(0.1563311078777302),
 'infamous': np.float64(-5.14653774791166),
 'army': np.float64(0.336035708196834),
 'conflict': np.float64(0.44061501667313263),
 'this': np.float64(0.9512264895383606),
 'paper': np.float64(0.7843053959287419),
 'considers': np.float64(-0.5835453036634246),
 'traditional': np.float64(0.7343665407442107),
 'problem': np.float64(0.7803366315710557),
 'resource': np.float64(0.21556418650474074),
 'allocation': np.float64(-0.8478159478269545),
 'schedulingjobs': np.float64(-42.14401324373498),
 'machines': np.float64(0.39020252164822217),
 'such': np.float64(0.8822223567983476),
 'recent': np.float64(0.6780391972273265),
 'application': np.float64(0.4837343991218795),
 'cloud': np.float64(0.39636363061877145),
 'computing': np.float64(0.41703270565788136),
 'jobsarrive': np.float64(-42.14401324373498),
 'online': np.float64(0.7717122559201612),
 'fashion': np.float64(0.41354331996770083),
 'capacity': np.float64(0.43239719634704843),
 'requirements': np.float64(0.3146050880342264),
 'high': np.float64(0.8446908901464261),

In [13]:
df.head()

,ID,Label,Text,word_count,tokens
0,25454,Google,We propose a new global entity disambiguation ...,33,"[we, propose, a, new, global, entity, disambig..."
1,5152,Google,Newton's laws and Newtonian mechanics in gener...,43,"[newton, 's, laws, and, newtonian, mechanics, ..."
2,27268,Google,3 April 2017 Last updated at 09:17 BST Demand ...,35,"[3, april, 2017, last, updated, at, 09:17, bst..."
3,29161,Google,Southern California contains a Mediterranean c...,32,"[southern, california, contains, a, mediterran..."
4,45531,Google,NASA scientists discovered cyclopropenylidene ...,33,"[nasa, scientists, discovered, cyclopropenylid..."

In [14]:
# Function to subsample a text
def subsample_text(text_tokens, keep_prob):
    return [token for token in text_tokens if random.random() > keep_prob[token]]

# Apply subsampling to the entire corpus
df['tokens_sub'] = df.apply(lambda row: subsample_text(row['tokens'], keep_prob), axis=1)
df.head()

,ID,Label,Text,word_count,tokens,tokens_sub
0,25454,Google,We propose a new global entity disambiguation ...,33,"[we, propose, a, new, global, entity, disambig...","[entity, disambiguation, ed, based, contextual..."
1,5152,Google,Newton's laws and Newtonian mechanics in gener...,43,"[newton, 's, laws, and, newtonian, mechanics, ...","[newton, newtonian, mechanics, developed, desc..."
2,27268,Google,3 April 2017 Last updated at 09:17 BST Demand ...,35,"[3, april, 2017, last, updated, at, 09:17, bst...","[3, april, updated, 09:17, bst, demand, proper..."
3,29161,Google,Southern California contains a Mediterranean c...,32,"[southern, california, contains, a, mediterran...","[southern, california, mediterranean, infreque..."
4,45531,Google,NASA scientists discovered cyclopropenylidene ...,33,"[nasa, scientists, discovered, cyclopropenylid...","[nasa, discovered, cyclopropenylidene, saturn,..."

In [15]:
# Print the original and subsampled corpus for comparison
print("Original corpus:", len([token for row in df['tokens'] for token in row]))
print("Original vocab length:", len(list(set([token for row in df['tokens'] for token in row]))))
print("Subsampled corpus:", len([token for row in df['tokens_sub'] for token in row]))
print("Subsampled vocab length:", len(list(set([token for row in df['tokens_sub'] for token in row]))))

Original corpus: 18528300
Original vocab length: 140934
Subsampled corpus: 5320627
Subsampled vocab length: 140934

## Word2Vec

In [16]:
# Vocabulary
vocab = list(set([token for row in df['tokens_sub'] for token in row]))
vocab[:5]

['blank2', 'beaufont', 'racks', 'sortable', 'fibrinogen']

In [17]:
# Id to token dictionary
id2tok = dict(enumerate(vocab))
print(list(id2tok.items())[:4])

# Token to id dictionary
tok2id = {token: i for (i, token) in id2tok.items()}
print(list(tok2id.items())[:4])

[(0, 'blank2'), (1, 'beaufont'), (2, 'racks'), (3, 'sortable')]
[('blank2', 0), ('beaufont', 1), ('racks', 2), ('sortable', 3)]

In [18]:
# Skip-grams windows
WINDOW_WIDTH = 5

def windowizer(tokens, wsize = WINDOW_WIDTH):
  out = []
  for i, wd in enumerate(tokens):
    target = tok2id[wd]
    window = [
      i + j for j in range(-wsize, wsize + 1, 1) if (i + j >= 0) & (i + j < len(tokens)) & (j != 0)
    ]
    out += [(target, tok2id[tokens[w]]) for w in window]
  return out

In [19]:
df["window"] = df.apply(lambda row: windowizer(row['tokens_sub']), axis=1)
df.head()

,ID,Label,Text,word_count,tokens,tokens_sub,window
0,25454,Google,We propose a new global entity disambiguation ...,33,"[we, propose, a, new, global, entity, disambig...","[entity, disambiguation, ed, based, contextual...","[(32804, 35857), (32804, 8299), (32804, 45213)..."
1,5152,Google,Newton's laws and Newtonian mechanics in gener...,43,"[newton, 's, laws, and, newtonian, mechanics, ...","[newton, newtonian, mechanics, developed, desc...","[(43667, 125870), (43667, 7431), (43667, 10432..."
2,27268,Google,3 April 2017 Last updated at 09:17 BST Demand ...,35,"[3, april, 2017, last, updated, at, 09:17, bst...","[3, april, updated, 09:17, bst, demand, proper...","[(105931, 67236), (105931, 7306), (105931, 688..."
3,29161,Google,Southern California contains a Mediterranean c...,32,"[southern, california, contains, a, mediterran...","[southern, california, mediterranean, infreque...","[(11442, 5420), (11442, 108625), (11442, 84415..."
4,45531,Google,NASA scientists discovered cyclopropenylidene ...,33,"[nasa, scientists, discovered, cyclopropenylid...","[nasa, discovered, cyclopropenylidene, saturn,...","[(74305, 23435), (74305, 119353), (74305, 2954..."

In [20]:
class Word2VecDataset(Dataset):
  def __init__(self, dataset, vocab_size):
    self.vocabsize = vocab_size
    self.dataset = dataset
    self.data = [pair for row in dataset['window'] for pair in row]

  def __len__(self):
    return len(self.data)

  def __getitem__(self, idx):
    return self.data[idx]

In [21]:
df_final = Word2VecDataset(
    df[['tokens_sub', 'window']],
    vocab_size = len(vocab)
)

df_final

In [22]:
BATCH_SIZE = 100

dataloader = DataLoader(
    df_final,
    batch_size = BATCH_SIZE,
    shuffle = True,
    num_workers = 0,
    pin_memory = True
)

In [23]:
len(dataloader)

480816

In [24]:
EMBED_DIM = 100

class Word2Vec(nn.Module):
  def __init__(self, vocab_size = len(vocab), embedding_size = EMBED_DIM):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size, embedding_size)
    self.expand = nn.Linear(embedding_size, vocab_size, bias=False)

  def forward(self, input):
    target_embedding = self.embedding(input)
    logits = self.expand(target_embedding)
    return logits

In [25]:
model = Word2Vec()
model

Word2Vec(
  (embedding): Embedding(140934, 100)
  (expand): Linear(in_features=100, out_features=140934, bias=False)
)

In [26]:
if torch.cuda.is_available():
  device = torch.device('cuda:0')
else:
  device = torch.device('cpu')
device

device(type='cpu')

In [27]:
model.to(device)

Word2Vec(
  (embedding): Embedding(140934, 100)
  (expand): Linear(in_features=100, out_features=140934, bias=False)
)

In [28]:
EPOCHS = 5
LEARNING_RATE = 5e-4
PATH = 'C:/Users/cinthia.nagahama.VERT/Documents/UMINHO/2 Semestre/Aprendizagem Profunda/trabalho'
accumulation_steps = 4  # Accumulate gradients over 4 batches

loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.AdamW(model.parameters(), lr = LEARNING_RATE)

def train(model, data, running_loss, epochs = 10):
  pbar = tqdm(range(epochs * len(data)))
  
  for epoch in range(epochs):
    # print(f"### {epoch} ###")
    epoch_loss = 0

    for sample_num, (target, context) in enumerate(data):
      # print(sample_num)
      target = target.to(device)
      context = context.to(device)

      optimizer.zero_grad()
      logits = model(input=context)
      loss = loss_fn(logits, target)

      if not sample_num % 10000:
          pbar.set_description(f'loss[{sample_num}] = {loss.item()}')

      epoch_loss += loss.item()
      loss.backward()
      optimizer.step()  # Update weights after accumulation_steps batches
      pbar.update(1)

    epoch_loss /= len(dataloader)
    running_loss.append(epoch_loss)
    torch.save({
      'epoch': epoch,
      'model_state_dict': model.state_dict(),
      'optimizer_state_dict': optimizer.state_dict(),
      'loss': loss
    }, PATH + f"model_{epoch}.pt")

  pbar.close()

In [31]:
running_loss = []

train(model, dataloader, running_loss, EPOCHS)

torch.save(model.state_dict(), f'{PATH}model.pt')

KeyboardInterrupt: